apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: person
  template:
    metadata:
      labels:
        app: person
    spec:
      containers:
      - name: person
        image: hiprabhat/ecommerce-person:v1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
